### ISSUE TITLE
Crash on java.lang.NumberFormatException during export

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/travel-behavior-analysis#24]
**Describe the bug**

Running on exporting the production data:

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "XXXXX"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at edu.usf.cutr.tba.utils.QueryDocumentSnapshotDeviceComparator.getDeviceComparableTime(QueryDocumentSnapshotDeviceComparator.java:48)
	at edu.usf.cutr.tba.utils.QueryDocumentSnapshotDeviceComparator.compare(QueryDocumentSnapshotDeviceComparator.java:35)
	at edu.usf.cutr.tba.utils.QueryDocumentSnapshotDeviceComparator.compare(QueryDocumentSnapshotDeviceComparator.java:29)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at edu.usf.cutr.tba.manager.TravelBehaviorDataAnalysisManager.processUserById(TravelBehaviorDataAnalysisManager.java:121)
	at edu.usf.cutr.tba.manager.TravelBehaviorDataAnalysisManager.analyzeAllTravelBehaviorData(TravelBehaviorDataAnalysisManager.java:89)
	at edu.usf.cutr.tba.manager.TravelBehaviorDataAnalysisManager.processData(TravelBehaviorDataAnalysisManager.java:73)
	at edu.usf.cutr.tba.ProcessorMain.main(ProcessorMain.java:120)
```

...where `XXXXX` is a long alpha numeric string.

**To Reproduce**
1. Run with command-line parameters `-keyFile "path/to/keyfile/key.json" -skipKMZ -outputDir myOutput`

**Expected behavior**
Export should complete without a crash

**Actual behavior**
Application crashed during export

**Desktop (please complete the following information):**
Master branch as of https://github.com/CUTR-at-USF/travel-behavior-analysis/commit/62ad9aab3383d9ec3cb9cf3fbb31d326a61e343e running on Windows 7 Enterprise with JDK 8.

**Comment by barbeau** [comment]
Looks like the issue is that early versions of device-information didn't use the timestamp for the document name, but used one of the random IDs instead. So this fails in the comparator:

```java
    @Override
    public int compare(QueryDocumentSnapshot o1, QueryDocumentSnapshot o2) {
        long t1 = getDeviceComparableTime(o1);
        long t2 = getDeviceComparableTime(o2);

        return Long.compare(t1, t2);
    }

    private long getDeviceComparableTime(QueryDocumentSnapshot o) {
        DeviceInformation devInfo = o.toObject(DeviceInformation.class);

        String timeStamp = devInfo.getTimestamp();
        if (timeStamp == null) {
            timeStamp = o.getId();
        }
        return Long.parseLong(timeStamp); // <-- This tries to parse an alphanumeric string
    }
```

So I think the best solution is to test if the timestamp is a `Long` there, and if not just assign https://docs.oracle.com/javase/7/docs/api/java/lang/Long.html#MIN_VALUE to it? The records without timestamp included and with a different-formatted names are the oldest ones...

**Comment by welozano** [comment]
I agree. I was not taking into account that early version of device-information didn't use timestamp for document name. I will implement the suggested solution.

**Comment by barbeau** [comment]
Actually, rather than using `Long.MIN_VALUE`, a better solution would be to parse off the leading number and use that instead. So they are values formatted like:

`122-99jklhgs-dfl...`
`123-j39j9g3g-oow...`

So if you parse off the part before the first `-`, the record `122` comes before `123`.

**Comment by welozano** [comment]
Does the part before `-` is always a number? or should I verify first and, if not a number then use Long.MIN_VALUE?

**Comment by barbeau** [comment]
The prefix should always be a integer, starting with `1` and incremented with each record. Given we're dealing with NoSQL database, though, it's probably best to assume that it may not be, and in that case use `Long.MIN_VALUE`.
